# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='no_of_threads',
            field=models.IntegerField(default=0),
        ),
    ]
