# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic_no_of_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='no_of_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='no_of_messages',
            field=models.IntegerField(default=0),
        ),
    ]
